services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
#    ports:
#      - "53:53/tcp"
#      - "53:53/udp"
#      - "8080:80/tcp"
#      - "8443:443/tcp"

    environment:
      FTLCONF_webserver_port: "8080o,8443os"
      TZ: 'America/Sao_Paulo'
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      FTLCONF_dns_listeningMode: 'LOCAL'

    volumes:
      - './etc-pihole:/etc/pihole'

    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE

    restart: unless-stopped
