headerStyle: boxedWidgets

title: Homelab

favicon: # seu_favicon

background:
  image: # sua_imagem
  blur: sm
  saturate: 50
#  brigthness: 50
#  opacity: 50

#theme: dark
#color: neutral

blockHighlights:
  levels:
    good: "bg-emerald-500/40 text-emerald-950 dark:bg-emerald-900/60 dark:text-emerald-400"
    warn: "bg-amber-300/30 text-amber-900 dark:bg-amber-900/30 dark:text-amber-200"
    danger: "bg-rose-700/45 text-rose-200 dark:bg-rose-950/70 dark:text-rose-400"

#maxBookmarkGroupColumns: 3
maxGroupColumns: 4
# showStats: true
statusStyle: "basic"
#bookmarksStyle: icons
# groupsInitiallyCollapsed: true
# disableCollapse: true
iconStyle: theme

layout:
  Network:
    style: column
    columns: 4
    icon: sh-netbox

  Administration:
    style: column
    columns: 4
    icon: sh-flowise

  Calendar:
    style: column
    columns: 4
    icon: sh-many-notes
